version: '3.6'

services:
  varnish:
    container_name: ${DOMAIN}_varnish
    build:
      context: ./services/varnish
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        VARNISH_MEMORY: ${VARNISH_MEMORY}
    environment:
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
    restart: always
    depends_on:
      - nginx

  nginx:
    container_name: ${DOMAIN}_nginx
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    restart: always
    volumes:
      - code:/code
    depends_on:
      - php

  php:
    container_name: ${DOMAIN}_php
    build:
      context: ./services/php
      args:
        PHP_VERSION: ${PHP_VERSION}
    restart: always
    volumes:
      - code:/code
    depends_on:
      - mysql
      - wordpress

  mysql:
    container_name: ${DOMAIN}_mysql
    image: mariadb:${MARIADB_VERSION}
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    container_name: ${DOMAIN}_wordpress
    build:
      context: ./services/wordpress
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    volumes:
      - code:/code
    command: sh -c "test -f /code/index.php ||
                    (set -ex;
                    curl -o wordpress.tar.gz -fSL \"https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz\";
                    tar -xzf wordpress.tar.gz --strip-components=1 -C /code;
                    rm wordpress.tar.gz;
                    cp /code/wp-config-sample.php /code/wp-config.php;
                    sed -i \"s/database_name_here/${MYSQL_DATABASE}/g\" /code/wp-config.php;
                    sed -i \"s/localhost/mysql/g\" /code/wp-config.php;
                    sed -i \"s/username_here/${MYSQL_USER}/g\" /code/wp-config.php;
                    sed -i \"s/password_here/${MYSQL_PASSWORD}/g\" /code/wp-config.php;
                    curl -o w3-total-cache.zip -fSL \"https://downloads.wordpress.org/plugin/w3-total-cache.${W3_TOTAL_CACHE_VERSION}.zip\";
                    unzip w3-total-cache.zip -d /code/wp-content/plugins/;
                    rm w3-total-cache.zip;
                    curl -o /code/wp-admin/wp-cli.phar -fSL \"https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar\";
                    chown -R www-data:www-data /code;)"

  exim:
    container_name: ${DOMAIN}_exim
    build:
      context: ./services/exim
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    dns: ${EXIM_DNS}
    restart: always

volumes:
    code:
    mysql_data: