version: '3.6'

services:
  varnish:
    container_name: ${DOMAIN}_varnish
    build:
      context: ./services/varnish
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        VARNISH_MEMORY: ${VARNISH_MEMORY}
    environment:
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
    restart: always
    depends_on:
      - nginx

  nginx:
    container_name: ${DOMAIN}_nginx
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    restart: always
    volumes:
      - code:/code
    depends_on:
      - wordpress

  mysql:
    container_name: ${DOMAIN}_mysql
    image: mariadb:${MARIADB_VERSION}
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: ${WORDPRESS_VERSION}
    container_name: wordpress
    volumes:
      - ./services/wordpressconfig/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./services/wordpressconfig/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./code:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_TABLE_PREFIX=${MYSQL_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${MYSQL_DB_HOST}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
    restart: always

  exim:
    container_name: ${DOMAIN}_exim
    build:
      context: ./services/exim
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    dns: ${EXIM_DNS}
    restart: always

volumes:
    code:
    mysql_data: